language: node_js
node_js:
- '8'
- '10'
env:
  global:
    secure: uXrKyLPeApA4mp5hHVnk0kpt1xKafKA3Cq8mrCC0EBdxmE5lzPIOuVysM8tcD9Q737G8Ob0gBWT3zbiUcT2ZZjc5kJu0IgREeTBIwqvJAUd93352vIppR88nQbJEzz/R2VnTfbaZhzh7XBCMhCc+qQFSYnsdN1cLASRSKS/ABkBZyY6VEkTm/cGVRdrkzRyeBuA1L4ZACVRTpCpIYY243cgBmIueZvZs5cwjx4LYhAtEtFvmtMYKscBmHROqzxz1fwnN/R8BMUV1uDPh13UigfTdmmexwA88YvRtKZfZRw8piFzU2llW/P5B8yzpADcTCueys6K8dNMjgWo6hJvWg1KZX02a0R+Fb3XUe+y+dAlsw7KWqqyGWt1f45GzG1MJ9jqJk77cZ0sjJF8euwqvb5vcMOD/xTVNRvush4IP48tbK7JPYOkTP1cp8IlmfxwhQfaOYC9Kh9nTcYxp6tlQZ55iia9SQzWIgyajut4jQ2+w7YEBdXop/P52+woz8BGQLGv1OaCoBZvY6IbtKwloqP40/6WNPmtuNfNUAbMzHBl6b/J2WYUN6mEhvZINmuWpv8VKAGyJ1WLSb+HrtpjPMABBNjAD1mQ5XJXzeAfFphFISA+T2ZnxFwCNm3hNNaTkwoKI+W4nsdV6NUGcjRzVOe29JToLfSaQZgJUW0VAevo=
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- npm run ci
after_script: greenkeeper-lockfile-upload
after_success: npm run coverage
deploy:
  provider: npm
  skip_cleanup: true
  email: tho.rucker@gmail.com
  api_key:
    secure: pVcP7JfD6sm4Hyy9/okL3rRV7LHAra6tbdLrBATsuMvPeipTzUDWfFNAhsr4BnPwMM0lrUGPv8UMitHs7fio/sSIqm4NhABBDas19RM6H/ke7+wEotPnizGcIeYV6t3DZrboZxfg1qliCp7ALu60HuOvgMR2cxn4WVlT01hAFSrJN2P/Vm8GlOSNqfY+ZB8M3KExyjImJpq44PC+I0KFA3+pGAmK6iPTZbkndlKClhxN/p8GohzAzXOZyzIlUDNOLSHd03mcGca1jBKB4+qBOwqkHebWxyAPOdfq2M24l3EsjSlY77hVLQ+eprnyVkwrfm1qGCQ9W/khgDt8RAEEo0zmliAB+uUJ368sxkS/1cwk2mPjG7QiO3rptpkmwBvUHujMYUe/XFoemaKeB5jrLQ9HmUgbNzkI6ct3QbSd6X7Yqv2kQ1nJS3f+9ugxe+vPAHyTW+XsfQD84oveion0IcCqBSAODAjovLq9IM/yg3KSPReUKkVUUMyfT5XvzWwdC2jEzU+mViivvvi7bL5qwzPMphE9/TzHg1bZwDTtBjoXpZGYviZ106uXQYIaDnJUmKzWUHxuQCc18HoDdg+OdlC8G7h78u6Lac9ax5Dt2ojvFg+uzen6SJfj01oJFZUwCEScjn/8/I3AzhKRNUMS0aimum2XGbTNq5N17yaucPI=
  on:
    tags: true
    repo: thrucker/transmog
    node: '8'
